<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.kod</string>
	</array>
	<key>name</key>
	<string>kod</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(if|else|for|to|end|while|break|continue|return|let|class)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|nil)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\#[A-Za-z_][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\#"[^"]*")</string>
			<key>name</key>
			<string>support.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=)[^=&gt;]</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language meta.label.identifier</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(let)\s*([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name meta.function.identifier</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_]*)\s*(=&gt;)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity meta.function.identifier</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\:[A-Za-z_][A-Za-z0-9_]*)\s*(=&gt;)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|\!=|&lt;|&lt;=|&gt;|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|\-|\/[^\/]|\*|\!|\&amp;|\|)=?</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\]|\{|\}|\(|\)|\,|\;|\.)</string>
			<key>name</key>
			<string>punctuation.separator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\/\/[^\r\n]*)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_]*)(?=\s*\()</string>
			<key>name</key>
			<string>entity.name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_]*)(?!\s*\()</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?=\.)([A-Za-z_][A-Za-z0-9_]*)(?=\s*\()</string>
			<key>name</key>
			<string>entity.name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?=\.)([A-Za-z_][A-Za-z0-9_]*)(?!\s*\()</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\:[A-Za-z_][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'.\'</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>0x[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kod</string>
	<key>uuid</key>
	<string>c99f17c6-9642-4847-b3ec-16e0580ebe16</string>
</dict>
</plist>
