<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.kod</string>
	</array>
	<key>name</key>
	<string>kod</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(if|else|for|end|while|break|return)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(byte|i8|int8|ubyte|u8|uint8)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(short|word|i16|int16|ushort|uword|u16|uint16)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(int|dword|i32|int32|uint|udword|u32|uint32)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(float|f32|float32|let)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(print)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=)[^=]</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|\!=|&lt;|&lt;=|&gt;|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|\-|\/|\*|\!|\&amp;|\|)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\]|\{|\}|\(|\)|,)</string>
			<key>name</key>
			<string>punctuation.definition</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;[^\r\n]*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_\.]*)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_\.]*)</string>
			<key>name</key>
			<string>storage.type.variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(include|bounds|debug)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'.\'</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>0x[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kod</string>
	<key>uuid</key>
	<string>c99f17c6-9642-4847-b3ec-16e0580ebe16</string>
</dict>
</plist>
